# Generated by Django 3.0.2 on 2020-01-30 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Game Name')),
                ('publish_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 30, 0, 39, 39, 702868))),
                ('publisher', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
