# Generated by Django 2.2.6 on 2020-01-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
    ]
