# Generated by Django 3.1.14 on 2026-02-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_total_correct', models.IntegerField(default=0)),
                ('note_total_attempts', models.IntegerField(default=0)),
                ('note_best_streak', models.IntegerField(default=0)),
                ('note_current_streak', models.IntegerField(default=0)),
                ('note_difficulty', models.CharField(default='beginner', max_length=20)),
                ('pitch_total_correct', models.IntegerField(default=0)),
                ('pitch_total_attempts', models.IntegerField(default=0)),
                ('pitch_best_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
