# Generated by Django 5.2.11 on 2026-02-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chord_best_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chord_current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chord_difficulty",
            field=models.CharField(default="beginner", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chord_total_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chord_total_correct",
            field=models.IntegerField(default=0),
        ),
    ]
