# Generated by Django 5.2.10 on 2026-02-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('note', 'Note Reading'), ('interval', 'Interval Training'), ('pitch', 'Pitch Identification')], max_length=20)),
                ('correct', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-correct', '-accuracy', '-best_streak'],
                'indexes': [models.Index(fields=['game', '-correct'], name='leaderboard_game_ceb80d_idx'), models.Index(fields=['game', 'created_at'], name='leaderboard_game_2e9c97_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('note', 'Note Reading'), ('interval', 'Interval Training'), ('pitch', 'Pitch Identification')], max_length=20)),
                ('week_start', models.DateField()),
                ('total_correct', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('sessions_played', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_correct', '-accuracy'],
                'indexes': [models.Index(fields=['game', 'week_start', '-total_correct'], name='leaderboard_game_440b13_idx')],
                'unique_together': {('user', 'game', 'week_start')},
            },
        ),
    ]
