# Generated by Django 5.2.10 on 2026-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.CharField(choices=[('note', 'Note Reading'), ('interval', 'Interval Training'), ('chord', 'Chord Identification'), ('pitch', 'Pitch Identification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyscore',
            name='game',
            field=models.CharField(choices=[('note', 'Note Reading'), ('interval', 'Interval Training'), ('chord', 'Chord Identification'), ('pitch', 'Pitch Identification')], max_length=20),
        ),
    ]
