# Generated by Django 5.2.10 on 2026-02-03 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_score_game_alter_weeklyscore_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='score',
            name='leaderboard_game_ceb80d_idx',
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='leaderboard_game_2e9c97_idx',
        ),
        migrations.RemoveIndex(
            model_name='weeklyscore',
            name='leaderboard_game_440b13_idx',
        ),
        migrations.AlterUniqueTogether(
            name='weeklyscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='score',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyscore',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyscore',
            unique_together={('user', 'game', 'difficulty', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', 'difficulty', '-correct'], name='leaderboard_game_36e733_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', 'difficulty', 'created_at'], name='leaderboard_game_dc8dde_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyscore',
            index=models.Index(fields=['game', 'difficulty', 'week_start', '-total_correct'], name='leaderboard_game_961d88_idx'),
        ),
    ]
